import type { Store } from "@types";

const initialState: Store = {
  baseUrl: "",
  secret: "",
  isBirthDateEmpty: false,
  remunerationAgreement: false,
  insuranceName: "",
  insuranceNumber: "",
  additionalInformation: "",
  additionalLegalInsurance: "",
  additionalLegalInsuranceExtended: "",
  carOwner: "",
  carOwnerExtended: "",
  relationshipOwnerDriver: "",
  waiverOnDrivingBanImportant: "",
  waiverOnDrivingBanImportantExtended: "false",
  files: {
    list: [],
    filesToUpload: [],
    completed: false,
    uploadingMore: false,
    category: null,
  },
  statuses: {
    getConfigJson: "idle",
    getAuthenticate: "idle",
    postFirstView: "idle",
    getSignature: "idle",
    postSign: "idle",
    postSignRemuneration: "idle",
    postInsuranceInformation: "idle",
    postClientSurvey: "idle",
    postFiles: "idle",
  },
  authentication: null,
  formStep: null,
  formTitle: "",
  formSubtitle: "",
  currentPage: null,
  variation: null,
  coverage: null,
  isLeadSwitched: false,
  isLeadSigning: false,
  activeAttachmentSection: null,
  noBoxOnStrafsachen: false,
  personal: {
    touched: [],
    isCorrect: false,
    isDirty: false,
    result: {
      salutation: false,
      firstName: false,
      lastName: false,
      birthName: false,
      birthDate: false,
      birthCity: false,
    },
    status: {
      salutation: "neutral",
      firstName: "neutral",
      lastName: "neutral",
      birthName: "neutral",
      birthDate: "neutral",
      birthCity: "neutral",
    },
  },
  address: {
    touched: [],
    isCorrect: false,
    isDirty: false,
    result: {
      street: false,
      houseNumber: false,
      postCode: false,
      city: false,
    },
    status: {
      street: "neutral",
      houseNumber: "neutral",
      postCode: "neutral",
      city: "neutral",
    },
  },
  checkout: {
    submitClickCount: 0,
    isMoneySectionShown: false,
    errors: [],
    mandatory: [],
  },
  attachment: {
    isCorrectInsurance: false,
    isCorrectFiles: false,
    isCorrectSurvey: false,
  },
  dialog: {
    name: null,
    position: null,
    size: null,
    payload: null,
  },
};

export default initialState;
